[package]
name = "transactions"
version = "0.1.0"
edition = "2021"

[dependencies]

solana-client = "2.0.4"
solana-sdk = "2.0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15.0"